// Generated by CoffeeScript 1.6.3
(function() {
  var index, lin_end, sl, speed, type_text;

  sl = ["line one", "line two", "line three", "line four", "line five"];

  lin_end = 0;

  index = 0;

  speed = 60;

  type_text = function() {
    var contents, row;
    contents = "";
    row = Math.max(0, index - 4);
    while (row < index) {
      contents += sl[row++] + "\r\n";
    }
    document.forms[0].elements[0].value = contents + sl[index].substring(0, lin_end) + "_";
    if (lin_end++ === sl[index].length) {
      lin_end = 0;
      index++;
      if (index !== sl.length) {
        return setTimeout(type_text, 1500);
      }
    } else {
      return setTimeout(type_text, speed);
    }
  };

  window.onload = function() {
    return type_text();
  };

}).call(this);
